# -*- coding: utf-8 -*-
"""CyberGuard

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RDyDaMHTfQSGnQUZ949YDlME0cUN-ShC
"""

import os
import platform
import psutil
import subprocess

def scan_for_malware():
    print("Scanning for malware...")
    if platform.system() == 'Windows':
        try:
            # Using Windows Defender for malware scanning
            result = subprocess.check_output('powershell.exe Get-MpComputerStatus', shell=True)
            print(result.decode())
        except Exception as e:
            print(f"Error scanning for malware on Windows: {e}")
    elif platform.system() == 'Linux':
        try:
            # Using ClamAV for malware scanning on Linux
            result = subprocess.check_output('clamscan --infected --recursive /home', shell=True)
            print(result.decode())
        except Exception as e:
            print(f"Error scanning for malware on Linux: {e}")
    else:
        print("Unsupported OS for malware scan.")

def check_firewall_status():
    print("Checking firewall status...")
    try:
        if platform.system() == 'Windows':
            output = subprocess.check_output('netsh advfirewall show allprofiles', shell=True)
            print(output.decode())
        elif platform.system() == 'Linux':
            output = subprocess.check_output('sudo ufw status', shell=True)
            print(output.decode())
        else:
            print("Unsupported OS for firewall check.")
    except Exception as e:
        print(f"Error checking firewall: {e}")

def check_system_security():
    print("Checking system security features...")
    if platform.system() == 'Windows':
        try:
            for proc in psutil.process_iter(['pid', 'name']):
                if 'MsMpEng.exe' in proc.info['name']:
                    print("Windows Defender is running.")
                    break
            else:
                print("Windows Defender is not running.")
        except Exception as e:
            print(f"Error checking security processes on Windows: {e}")
    elif platform.system() == 'Linux':
        try:
            antivirus_processes = ['clamd', 'freshclam', 'clamav']
            for proc in psutil.process_iter(['pid', 'name']):
                if proc.info['name'] in antivirus_processes:
                    print(f"{proc.info['name']} is running.")
                    break
            else:
                print("No ClamAV processes running.")
        except Exception as e:
            print(f"Error checking security processes on Linux: {e}")
    else:
        print("Unsupported OS for security check.")

def main():
    print("Pre-investigation of device's health and vulnerabilities...")
    scan_for_malware()
    check_firewall_status()
    check_system_security()
    print("Check complete.")

if __name__ == '__main__':
    main()