# -*- coding: utf-8 -*-
"""PowerConsump

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16jPQif8M2UASRDQwjwnALO9rqTRVDmg9
"""

import psutil

cpu_usage = psutil.cpu_percent(interval=1)
print(f"CPU Usage: {cpu_usage}%")